/**
 * GENERATED by tools/build-city-atlas.mjs — do not edit by hand.
 *
 * Frame rectangles inside public/images/city/city-atlas.png, which is packed
 * from the Kenney CC0 pack kept intact under src/assets/source/kenny/.
 * Semantic meaning lives in cityArt.ts; this file is only geometry.
 */
export const ATLAS_URL = 'images/city/city-atlas.png';
export const ATLAS_TILE = 16;
export interface Frame { x: number; y: number; w: number; h: number }
export const FRAMES = {
    arrowE: {
        x: 186,
        y: 34,
        w: 16,
        h: 16
    },
    arrowN: {
        x: 203,
        y: 34,
        w: 16,
        h: 16
    },
    arrowS: {
        x: 220,
        y: 34,
        w: 16,
        h: 16
    },
    arrowW: {
        x: 237,
        y: 34,
        w: 16,
        h: 16
    },
    awningGreen: {
        x: 1,
        y: 59,
        w: 16,
        h: 16
    },
    awningOrange: {
        x: 18,
        y: 59,
        w: 16,
        h: 16
    },
    bush: {
        x: 35,
        y: 59,
        w: 16,
        h: 16
    },
    car_amber_E: {
        x: 190,
        y: 1,
        w: 36,
        h: 24
    },
    car_amber_N: {
        x: 52,
        y: 1,
        w: 22,
        h: 29
    },
    car_amber_S: {
        x: 75,
        y: 1,
        w: 22,
        h: 29
    },
    car_amber_W: {
        x: 1,
        y: 34,
        w: 36,
        h: 24
    },
    car_green_E: {
        x: 38,
        y: 34,
        w: 36,
        h: 24
    },
    car_green_N: {
        x: 98,
        y: 1,
        w: 22,
        h: 29
    },
    car_green_S: {
        x: 121,
        y: 1,
        w: 22,
        h: 29
    },
    car_green_W: {
        x: 75,
        y: 34,
        w: 36,
        h: 24
    },
    car_silver_E: {
        x: 112,
        y: 34,
        w: 36,
        h: 24
    },
    car_silver_N: {
        x: 144,
        y: 1,
        w: 22,
        h: 29
    },
    car_silver_S: {
        x: 167,
        y: 1,
        w: 22,
        h: 29
    },
    car_silver_W: {
        x: 149,
        y: 34,
        w: 36,
        h: 24
    },
    cone: {
        x: 52,
        y: 59,
        w: 16,
        h: 16
    },
    crateFruit: {
        x: 69,
        y: 59,
        w: 16,
        h: 16
    },
    crateVeg: {
        x: 86,
        y: 59,
        w: 16,
        h: 16
    },
    dirt: {
        x: 103,
        y: 59,
        w: 16,
        h: 16
    },
    doorHome: {
        x: 120,
        y: 59,
        w: 16,
        h: 16
    },
    doorStore: {
        x: 137,
        y: 59,
        w: 16,
        h: 16
    },
    grassA: {
        x: 154,
        y: 59,
        w: 16,
        h: 16
    },
    grassB: {
        x: 171,
        y: 59,
        w: 16,
        h: 16
    },
    plot: {
        x: 188,
        y: 59,
        w: 16,
        h: 16
    },
    plotWorn: {
        x: 205,
        y: 59,
        w: 16,
        h: 16
    },
    road0: {
        x: 222,
        y: 59,
        w: 16,
        h: 16
    },
    road1: {
        x: 239,
        y: 59,
        w: 16,
        h: 16
    },
    road10: {
        x: 1,
        y: 76,
        w: 16,
        h: 16
    },
    road11: {
        x: 18,
        y: 76,
        w: 16,
        h: 16
    },
    road12: {
        x: 35,
        y: 76,
        w: 16,
        h: 16
    },
    road13: {
        x: 52,
        y: 76,
        w: 16,
        h: 16
    },
    road14: {
        x: 69,
        y: 76,
        w: 16,
        h: 16
    },
    road15: {
        x: 86,
        y: 76,
        w: 16,
        h: 16
    },
    road2: {
        x: 103,
        y: 76,
        w: 16,
        h: 16
    },
    road3: {
        x: 120,
        y: 76,
        w: 16,
        h: 16
    },
    road4: {
        x: 137,
        y: 76,
        w: 16,
        h: 16
    },
    road5: {
        x: 154,
        y: 76,
        w: 16,
        h: 16
    },
    road6: {
        x: 171,
        y: 76,
        w: 16,
        h: 16
    },
    road7: {
        x: 188,
        y: 76,
        w: 16,
        h: 16
    },
    road8: {
        x: 205,
        y: 76,
        w: 16,
        h: 16
    },
    road9: {
        x: 222,
        y: 76,
        w: 16,
        h: 16
    },
    roof_grey_b: {
        x: 239,
        y: 76,
        w: 16,
        h: 16
    },
    roof_grey_bl: {
        x: 1,
        y: 93,
        w: 16,
        h: 16
    },
    roof_grey_br: {
        x: 18,
        y: 93,
        w: 16,
        h: 16
    },
    roof_grey_l: {
        x: 35,
        y: 93,
        w: 16,
        h: 16
    },
    roof_grey_mid: {
        x: 52,
        y: 93,
        w: 16,
        h: 16
    },
    roof_grey_r: {
        x: 69,
        y: 93,
        w: 16,
        h: 16
    },
    roof_grey_t: {
        x: 86,
        y: 93,
        w: 16,
        h: 16
    },
    roof_grey_tl: {
        x: 103,
        y: 93,
        w: 16,
        h: 16
    },
    roof_grey_tr: {
        x: 120,
        y: 93,
        w: 16,
        h: 16
    },
    roof_pale_b: {
        x: 137,
        y: 93,
        w: 16,
        h: 16
    },
    roof_pale_bl: {
        x: 154,
        y: 93,
        w: 16,
        h: 16
    },
    roof_pale_br: {
        x: 171,
        y: 93,
        w: 16,
        h: 16
    },
    roof_pale_l: {
        x: 188,
        y: 93,
        w: 16,
        h: 16
    },
    roof_pale_mid: {
        x: 205,
        y: 93,
        w: 16,
        h: 16
    },
    roof_pale_r: {
        x: 222,
        y: 93,
        w: 16,
        h: 16
    },
    roof_pale_t: {
        x: 239,
        y: 93,
        w: 16,
        h: 16
    },
    roof_pale_tl: {
        x: 1,
        y: 110,
        w: 16,
        h: 16
    },
    roof_pale_tr: {
        x: 18,
        y: 110,
        w: 16,
        h: 16
    },
    roof_red_b: {
        x: 35,
        y: 110,
        w: 16,
        h: 16
    },
    roof_red_bl: {
        x: 52,
        y: 110,
        w: 16,
        h: 16
    },
    roof_red_br: {
        x: 69,
        y: 110,
        w: 16,
        h: 16
    },
    roof_red_l: {
        x: 86,
        y: 110,
        w: 16,
        h: 16
    },
    roof_red_mid: {
        x: 103,
        y: 110,
        w: 16,
        h: 16
    },
    roof_red_r: {
        x: 120,
        y: 110,
        w: 16,
        h: 16
    },
    roof_red_t: {
        x: 137,
        y: 110,
        w: 16,
        h: 16
    },
    roof_red_tl: {
        x: 154,
        y: 110,
        w: 16,
        h: 16
    },
    roof_red_tr: {
        x: 171,
        y: 110,
        w: 16,
        h: 16
    },
    roof_tan_b: {
        x: 188,
        y: 110,
        w: 16,
        h: 16
    },
    roof_tan_bl: {
        x: 205,
        y: 110,
        w: 16,
        h: 16
    },
    roof_tan_br: {
        x: 222,
        y: 110,
        w: 16,
        h: 16
    },
    roof_tan_l: {
        x: 239,
        y: 110,
        w: 16,
        h: 16
    },
    roof_tan_mid: {
        x: 1,
        y: 127,
        w: 16,
        h: 16
    },
    roof_tan_r: {
        x: 18,
        y: 127,
        w: 16,
        h: 16
    },
    roof_tan_t: {
        x: 35,
        y: 127,
        w: 16,
        h: 16
    },
    roof_tan_tl: {
        x: 52,
        y: 127,
        w: 16,
        h: 16
    },
    roof_tan_tr: {
        x: 69,
        y: 127,
        w: 16,
        h: 16
    },
    shopGlass: {
        x: 86,
        y: 127,
        w: 16,
        h: 16
    },
    shopGlassL: {
        x: 103,
        y: 127,
        w: 16,
        h: 16
    },
    shopGlassR: {
        x: 120,
        y: 127,
        w: 16,
        h: 16
    },
    signBar: {
        x: 137,
        y: 127,
        w: 16,
        h: 16
    },
    signDots: {
        x: 154,
        y: 127,
        w: 16,
        h: 16
    },
    tree_amber: {
        x: 1,
        y: 1,
        w: 16,
        h: 32
    },
    tree_green: {
        x: 18,
        y: 1,
        w: 16,
        h: 32
    },
    tree_pine: {
        x: 35,
        y: 1,
        w: 16,
        h: 32
    },
    wall_brick_l: {
        x: 171,
        y: 127,
        w: 16,
        h: 16
    },
    wall_brick_m: {
        x: 188,
        y: 127,
        w: 16,
        h: 16
    },
    wall_brick_one: {
        x: 205,
        y: 127,
        w: 16,
        h: 16
    },
    wall_brick_r: {
        x: 222,
        y: 127,
        w: 16,
        h: 16
    },
    wall_sand_l: {
        x: 239,
        y: 127,
        w: 16,
        h: 16
    },
    wall_sand_m: {
        x: 1,
        y: 144,
        w: 16,
        h: 16
    },
    wall_sand_one: {
        x: 18,
        y: 144,
        w: 16,
        h: 16
    },
    wall_sand_r: {
        x: 35,
        y: 144,
        w: 16,
        h: 16
    },
    wall_stone_l: {
        x: 52,
        y: 144,
        w: 16,
        h: 16
    },
    wall_stone_m: {
        x: 69,
        y: 144,
        w: 16,
        h: 16
    },
    wall_stone_one: {
        x: 86,
        y: 144,
        w: 16,
        h: 16
    },
    wall_stone_r: {
        x: 103,
        y: 144,
        w: 16,
        h: 16
    },
    windowFlat: {
        x: 120,
        y: 144,
        w: 16,
        h: 16
    },
    windowHome: {
        x: 137,
        y: 144,
        w: 16,
        h: 16
    }
} as const;
export type FrameName = keyof typeof FRAMES;
