import assert from 'node:assert/strict';
import {test} from 'node:test';
import {createCity,place,stepCity,parseCity,type City,type Point,type Trip} from './cityModel.ts';
import {applyRoadDirections} from './cityDirectionEdits.ts';
import {roundaboutIndex} from './cityRoundabouts.ts';
import {controlAt} from './cityTraffic.ts';
const points=(pairs:number[][]):Point[]=>pairs.map(([x,y])=>({x,y}));
const ring=points([[14,14],[15,14],[16,14],[16,15],[16,16],[15,16],[14,16],[14,15],[14,14]]);
function town(){const c=createCity();c.funds=100000;c.tutorial!.status='complete';c.map={x:0,y:0,width:32,height:32};for(const p of ring)place(c,'road',p.x,p.y);for(let n=10;n<=20;n++)if(n<14||n>16){place(c,'road',n,15);place(c,'road',15,n);}assert.ok(applyRoadDirections(c,ring,'forward').ok);return c;}
function trip(c:City,path:Point[],progress:number):Trip {const t:Trip={id:c.nextId++,homeId:c.nextId,storeId:0,path,progress,wait:0,hold:0};c.trips.push(t);return t;}
const incoming=points([[12,15],[13,15],[14,15],[14,14],[15,14],[16,14],[16,15],[17,15],[18,15],[19,15]]);
test('recognizes a road ring around empty land, but an open ring is ordinary roads',()=>{const c=town();assert.equal(roundaboutIndex(c).rings.length,1);const broken=structuredClone(c);broken.roads=broken.roads.filter(p=>p.x!==14||p.y!==14);assert.equal(roundaboutIndex(broken).rings.length,0);});
test('roundabout entrant accepts an empty local gap without mandatory stop dwell',()=>{const c=town(),t=trip(c,incoming,1.49);stepCity(c,.025);assert.ok(t.progress>1.5,'free entry should roll past the yield line');assert.equal(t.hold,0);});
test('roundabout entrant waits for nearby circulation without stopping the circulating vehicle',()=>{const c=town();const entering=trip(c,incoming,1.49);const circulating=trip(c,points([[14,16],[14,15],[14,14],[15,14],[16,14],[16,15],[17,15],[18,15]]),.49);stepCity(c,.025);assert.ok(entering.progress<=1.5,'entrant yields at the boundary');assert.ok(circulating.progress>.5,'circulation has priority even when inserted after entrant');});
test('a distant circulating vehicle does not require the whole roundabout to become empty',()=>{const c=town(),entering=trip(c,incoming,1.49);trip(c,points([[16,14],[16,15],[16,16],[15,16],[14,16],[14,15],[14,14]]),0);stepCity(c,.025);assert.ok(entering.progress>1.5,'entry accepts a safe local gap while another car remains on the ring');});
test('old all-way stop does not impose a dwell on circulating traffic after recognition',()=>{const c=town();c.controls.push({x:14,y:15,kind:'stop',preset:'balanced',paid:25});const t=trip(c,points([[14,16],[14,15],[14,14],[15,14],[16,14],[16,15],[17,15],[18,15]]),.49);stepCity(c,.025);assert.ok(t.progress>.5);assert.equal(t.hold,0);assert.ok(c.controls.length,'original control remains recoverable');});
test('roundabout recognition and real household position survive reload with completed returns',()=>{let c=town();place(c,'home',10,13);place(c,'store',18,13);assert.equal(c.buildings.length,2);let reloaded=false;for(let i=0;i<7200;i++){stepCity(c,.025);if(!reloaded&&c.trips.some(t=>t.progress>1)){const loaded=parseCity(JSON.parse(JSON.stringify(c)));assert.ok(loaded);assert.deepEqual(loaded.trips,c.trips);assert.equal(roundaboutIndex(loaded).rings.length,1);c=loaded;reloaded=true;}}assert.ok(reloaded);assert.ok(c.history.some(h=>h.service?.purpose==='shopping'),'real physical shopping return completes');assert.equal(c.accidentCount,0);});
test('an intentionally painted closed one-way loop around a block also gets entry yields',()=>{const c=createCity();c.funds=100000;c.tutorial!.status='complete';c.map={x:0,y:0,width:32,height:32};const loop:Point[]=[];for(let x=10;x<18;x++)loop.push({x,y:10});for(let y=10;y<18;y++)loop.push({x:18,y});for(let x=18;x>10;x--)loop.push({x,y:18});for(let y=18;y>10;y--)loop.push({x:10,y});loop.push(loop[0]);for(const p of loop)place(c,'road',p.x,p.y);for(const p of points([[9,14],[8,14],[19,14],[20,14]]))place(c,'road',p.x,p.y);place(c,'home',12,12);assert.equal(c.buildings.length,1);assert.ok(applyRoadDirections(c,loop,'forward').ok);assert.equal(roundaboutIndex(c).rings.length,1);});

test('a physical road chord through the loop excludes ambiguous roundabout recognition',()=>{const c=town();place(c,'road',15,15);assert.equal(roundaboutIndex(c).rings.length,0);});
test('a roundabout yield does not authorize driving through a closed exit',()=>{const c=town();c.closures.push({x:17,y:15});const t=trip(c,points([[16,14],[16,15],[17,15],[18,15],[19,15]]),.49);for(let i=0;i<80;i++){stepCity(c,.025);const p=t.path[Math.min(t.path.length-1,Math.ceil(t.progress-.5-1e-9))];assert.ok(p.x!==17||p.y!==15,'physical closure remains impassable');}assert.equal(c.completed,0);c.closures=[];for(let i=0;i<400;i++)stepCity(c,.025);assert.equal(c.completed,1,'opening exit permits actual completion');});
for(let turns=1;turns<=3;turns++)test(`roundabout entry ${turns+1} gives priority to nearby circulating traffic`,()=>{const c=town();const rotate=(path:Point[])=>path.map(p=>{let {x,y}=p;for(let n=0;n<turns;n++)[x,y]=[30-y,x];return {x,y};});const entrant=trip(c,rotate(incoming),1.49);const circulating=trip(c,rotate(points([[14,16],[14,15],[14,14],[15,14],[16,14],[16,15],[17,15],[18,15]])),.49);stepCity(c,.025);assert.ok(entrant.progress<=1.5);assert.ok(circulating.progress>.5);});

test('traffic light immediately beside a roundabout still controls its own intersection',()=>{const c=town();place(c,'road',13,14);place(c,'signal',13,15);assert.equal(controlAt(c,{x:13,y:15})?.kind,'signal');assert.equal(controlAt(c,{x:14,y:15}),undefined,'signal cannot stop circulation');const t=trip(c,incoming,.49);stepCity(c,.025);assert.ok(t.progress<=.5,'red still holds incoming east-west traffic at adjacent junction');});
