import assert from 'node:assert/strict';
import {test} from 'node:test';
import {createCity,place,stepCity,parseCity,type Trip} from './cityModel.ts';
import {applyRoadDirections} from './cityDirectionEdits.ts';
import {travelLaneOffset} from './cityTraffic.ts';
const points=(pairs:number[][])=>pairs.map(([x,y])=>({x,y}));
function city(){const c=createCity();c.funds=100000;c.tutorial!.status='complete';c.map={x:0,y:0,width:32,height:32};return c;}
test('saved second-lane bend recovery reserves physical space, reloads mid-merge and takes a real detour home',()=>{let c=city();const path=points([[10,10],[11,10],[12,10],[12,11],[13,11],[14,11],[15,11]]);for(const p of path)place(c,'road',p.x,p.y);assert.ok(applyRoadDirections(c,path,'forward').ok);for(const p of points([[12,9],[13,9],[14,9],[15,9],[15,10]]))place(c,'road',p.x,p.y);place(c,'home',14,12,2);const home=c.buildings[0];if(c.nextId%2)c.nextId++;let t:Trip={id:c.nextId++,homeId:home.id,storeId:0,phase:'returning',path,progress:0,wait:0,hold:0};c.trips=[t];let reached=false;for(let n=0;n<200;n++){stepCity(c,.025);if(t.trafficLane===1&&t.progress===2){reached=true;break;}}assert.ok(reached);c.closures.push(path[3]);let reloaded=false;for(let n=0;n<1600;n++){stepCity(c,.025);if(!reloaded&&t.laneChange?.to===0&&t.laneChange.shift>0){const before=travelLaneOffset(t);const loaded=parseCity(JSON.parse(JSON.stringify(c)));assert.ok(loaded,'bend recovery save validates');c=loaded;t=c.trips.find(v=>v.id===t.id)!;assert.equal(travelLaneOffset(t),before);reloaded=true;}}assert.ok(reloaded);assert.ok(c.completed>=1);assert.equal(c.accidentCount,0);});
for(const kind of ['crashed','working','parked'] as const)test(`${kind} second-lane body preserves its saved physical side without preventing legitimate incident recovery`,()=>{const phase=kind==='parked'?'working':kind;let c=city();const road=Array.from({length:17},(_,x)=>({x,y:6}));for(const p of road)place(c,'road',p.x,p.y);assert.ok(applyRoadDirections(c,kind==='parked'?road.slice(0,9):road,'forward').ok);place(c,'home',3,4);place(c,'policeStation',0,4);const home=c.buildings.find(b=>b.kind==='home')!,station=c.buildings.find(b=>b.kind==='policeStation')!;for(let x=1;x<=8;x++)place(c,'road',x,10);for(let y=7;y<10;y++){place(c,'road',1,y);place(c,'road',8,y);}const incident={id:c.nextId++,x:9,y:6,severity:'minor' as const,status:'active' as const,createdAt:0,required:['police' as const],completedServices:[],rescueDeadline:null,outcome:'none' as const};c.incidents=[incident];c.accidentCount=1;const t:Trip={id:c.nextId++,homeId:phase==='crashed'?home.id:0,storeId:0,path:[{x:phase==='crashed'?9:8,y:6}],progress:0,wait:0,hold:0,phase,trafficLane:1,incidentId:incident.id,...(phase==='working'?{service:'police' as const,stationId:station.id,workRemaining:1,...(kind==='parked'?{sceneParked:true}:{})}:{})};c.trips=[t];const loaded=parseCity(JSON.parse(JSON.stringify(c)));assert.ok(loaded,'stationary lane metadata must not reject a valid incident save');c=loaded;if(kind==='parked'){assert.ok(applyRoadDirections(c,road.slice(0,9),'two-way').ok);assert.ok(parseCity(JSON.parse(JSON.stringify(c))),'removing final directions beside parked crew must preserve save validity');}assert.equal(travelLaneOffset(c.trips[0]),1);stepCity(c,.025);assert.equal(travelLaneOffset(c.trips.find(v=>v.id===t.id)!),1,'stationary body does not jump sideways on next tick');for(let n=0;n<7200;n++)stepCity(c,.025);assert.ok(c.incidents[0].completedServices.includes('police'));assert.ok(!c.trips.some(v=>v.id===t.id),'wreck clears or working crew physically returns');});
