/**
 * GENERATED by tools/build-city-atlas.mjs — do not edit by hand.
 *
 * Frame rectangles inside public/images/city/city-atlas.png, which is packed
 * from the Kenney CC0 pack, home lots and approved service buildings and vehicles.
 * See docs/artwork/{housing,service-buildings,service-vehicles}/README.md for provenance.
 * Semantic meaning lives in cityArt.ts; this file is only geometry.
 */
export const ATLAS_URL = 'images/city/city-atlas.png';
export const ATLAS_TILE = 16;
export interface Frame { x: number; y: number; w: number; h: number }
export const FRAMES = {
    apartment_1_E: {
        x: 1,
        y: 1,
        w: 64,
        h: 64
    },
    apartment_1_N: {
        x: 66,
        y: 1,
        w: 64,
        h: 64
    },
    apartment_1_S: {
        x: 131,
        y: 1,
        w: 64,
        h: 64
    },
    apartment_1_W: {
        x: 196,
        y: 1,
        w: 64,
        h: 64
    },
    apartment_2_E_E_0: {
        x: 261,
        y: 1,
        w: 64,
        h: 64
    },
    apartment_2_E_E_1: {
        x: 326,
        y: 1,
        w: 64,
        h: 64
    },
    apartment_2_E_E_2: {
        x: 391,
        y: 1,
        w: 64,
        h: 64
    },
    apartment_2_E_N_0: {
        x: 1,
        y: 66,
        w: 64,
        h: 64
    },
    apartment_2_E_N_1: {
        x: 66,
        y: 66,
        w: 64,
        h: 64
    },
    apartment_2_E_N_2: {
        x: 131,
        y: 66,
        w: 64,
        h: 64
    },
    apartment_2_E_N_3: {
        x: 196,
        y: 66,
        w: 64,
        h: 64
    },
    apartment_2_E_S_0: {
        x: 261,
        y: 66,
        w: 64,
        h: 64
    },
    apartment_2_E_S_1: {
        x: 326,
        y: 66,
        w: 64,
        h: 64
    },
    apartment_2_E_S_2: {
        x: 391,
        y: 66,
        w: 64,
        h: 64
    },
    apartment_2_E_S_3: {
        x: 1,
        y: 131,
        w: 64,
        h: 64
    },
    apartment_2_E_W_0: {
        x: 66,
        y: 131,
        w: 64,
        h: 64
    },
    apartment_2_E_W_1: {
        x: 131,
        y: 131,
        w: 64,
        h: 64
    },
    apartment_2_E_W_2: {
        x: 196,
        y: 131,
        w: 64,
        h: 64
    },
    apartment_2_E_W_3: {
        x: 261,
        y: 131,
        w: 64,
        h: 64
    },
    apartment_2_N_E_0: {
        x: 326,
        y: 131,
        w: 64,
        h: 64
    },
    apartment_2_N_E_1: {
        x: 391,
        y: 131,
        w: 64,
        h: 64
    },
    apartment_2_N_E_2: {
        x: 1,
        y: 196,
        w: 64,
        h: 64
    },
    apartment_2_N_E_3: {
        x: 66,
        y: 196,
        w: 64,
        h: 64
    },
    apartment_2_N_N_0: {
        x: 131,
        y: 196,
        w: 64,
        h: 64
    },
    apartment_2_N_N_1: {
        x: 196,
        y: 196,
        w: 64,
        h: 64
    },
    apartment_2_N_N_2: {
        x: 261,
        y: 196,
        w: 64,
        h: 64
    },
    apartment_2_N_S_0: {
        x: 326,
        y: 196,
        w: 64,
        h: 64
    },
    apartment_2_N_S_1: {
        x: 391,
        y: 196,
        w: 64,
        h: 64
    },
    apartment_2_N_S_2: {
        x: 1,
        y: 261,
        w: 64,
        h: 64
    },
    apartment_2_N_S_3: {
        x: 66,
        y: 261,
        w: 64,
        h: 64
    },
    apartment_2_N_W_0: {
        x: 131,
        y: 261,
        w: 64,
        h: 64
    },
    apartment_2_N_W_1: {
        x: 196,
        y: 261,
        w: 64,
        h: 64
    },
    apartment_2_N_W_2: {
        x: 261,
        y: 261,
        w: 64,
        h: 64
    },
    apartment_2_N_W_3: {
        x: 326,
        y: 261,
        w: 64,
        h: 64
    },
    apartment_2_S_E_0: {
        x: 391,
        y: 261,
        w: 64,
        h: 64
    },
    apartment_2_S_E_1: {
        x: 1,
        y: 326,
        w: 64,
        h: 64
    },
    apartment_2_S_E_2: {
        x: 66,
        y: 326,
        w: 64,
        h: 64
    },
    apartment_2_S_E_3: {
        x: 131,
        y: 326,
        w: 64,
        h: 64
    },
    apartment_2_S_N_0: {
        x: 196,
        y: 326,
        w: 64,
        h: 64
    },
    apartment_2_S_N_1: {
        x: 261,
        y: 326,
        w: 64,
        h: 64
    },
    apartment_2_S_N_2: {
        x: 326,
        y: 326,
        w: 64,
        h: 64
    },
    apartment_2_S_N_3: {
        x: 391,
        y: 326,
        w: 64,
        h: 64
    },
    apartment_2_S_S_1: {
        x: 1,
        y: 391,
        w: 64,
        h: 64
    },
    apartment_2_S_S_2: {
        x: 66,
        y: 391,
        w: 64,
        h: 64
    },
    apartment_2_S_S_3: {
        x: 131,
        y: 391,
        w: 64,
        h: 64
    },
    apartment_2_S_W_0: {
        x: 196,
        y: 391,
        w: 64,
        h: 64
    },
    apartment_2_S_W_1: {
        x: 261,
        y: 391,
        w: 64,
        h: 64
    },
    apartment_2_S_W_2: {
        x: 326,
        y: 391,
        w: 64,
        h: 64
    },
    apartment_2_S_W_3: {
        x: 391,
        y: 391,
        w: 64,
        h: 64
    },
    apartment_2_W_E_0: {
        x: 1,
        y: 456,
        w: 64,
        h: 64
    },
    apartment_2_W_E_1: {
        x: 66,
        y: 456,
        w: 64,
        h: 64
    },
    apartment_2_W_E_2: {
        x: 131,
        y: 456,
        w: 64,
        h: 64
    },
    apartment_2_W_E_3: {
        x: 196,
        y: 456,
        w: 64,
        h: 64
    },
    apartment_2_W_N_0: {
        x: 261,
        y: 456,
        w: 64,
        h: 64
    },
    apartment_2_W_N_1: {
        x: 326,
        y: 456,
        w: 64,
        h: 64
    },
    apartment_2_W_N_2: {
        x: 391,
        y: 456,
        w: 64,
        h: 64
    },
    apartment_2_W_N_3: {
        x: 1,
        y: 521,
        w: 64,
        h: 64
    },
    apartment_2_W_S_0: {
        x: 66,
        y: 521,
        w: 64,
        h: 64
    },
    apartment_2_W_S_1: {
        x: 131,
        y: 521,
        w: 64,
        h: 64
    },
    apartment_2_W_S_2: {
        x: 196,
        y: 521,
        w: 64,
        h: 64
    },
    apartment_2_W_S_3: {
        x: 261,
        y: 521,
        w: 64,
        h: 64
    },
    apartment_2_W_W_1: {
        x: 326,
        y: 521,
        w: 64,
        h: 64
    },
    apartment_2_W_W_2: {
        x: 391,
        y: 521,
        w: 64,
        h: 64
    },
    apartment_2_W_W_3: {
        x: 1,
        y: 586,
        w: 64,
        h: 64
    },
    arrowE: {
        x: 260,
        y: 1348,
        w: 16,
        h: 16
    },
    arrowN: {
        x: 277,
        y: 1348,
        w: 16,
        h: 16
    },
    arrowS: {
        x: 294,
        y: 1348,
        w: 16,
        h: 16
    },
    arrowW: {
        x: 311,
        y: 1348,
        w: 16,
        h: 16
    },
    awningGreen: {
        x: 328,
        y: 1348,
        w: 16,
        h: 16
    },
    awningOrange: {
        x: 345,
        y: 1348,
        w: 16,
        h: 16
    },
    barrierOrange: {
        x: 362,
        y: 1348,
        w: 16,
        h: 16
    },
    barrierWarning: {
        x: 379,
        y: 1348,
        w: 16,
        h: 16
    },
    barrierWarningVertical: {
        x: 396,
        y: 1348,
        w: 16,
        h: 16
    },
    barrierYellow: {
        x: 413,
        y: 1348,
        w: 16,
        h: 16
    },
    building_fireStation_E: {
        x: 131,
        y: 1171,
        w: 32,
        h: 48
    },
    building_fireStation_N: {
        x: 50,
        y: 1236,
        w: 48,
        h: 32
    },
    building_fireStation_S: {
        x: 99,
        y: 1236,
        w: 48,
        h: 32
    },
    building_fireStation_W: {
        x: 164,
        y: 1171,
        w: 32,
        h: 48
    },
    building_hospital_E: {
        x: 197,
        y: 1171,
        w: 32,
        h: 48
    },
    building_hospital_N: {
        x: 148,
        y: 1236,
        w: 48,
        h: 32
    },
    building_hospital_S: {
        x: 197,
        y: 1236,
        w: 48,
        h: 32
    },
    building_hospital_W: {
        x: 230,
        y: 1171,
        w: 32,
        h: 48
    },
    building_policeStation_E: {
        x: 263,
        y: 1171,
        w: 32,
        h: 48
    },
    building_policeStation_N: {
        x: 246,
        y: 1236,
        w: 48,
        h: 32
    },
    building_policeStation_S: {
        x: 295,
        y: 1236,
        w: 48,
        h: 32
    },
    building_policeStation_W: {
        x: 296,
        y: 1171,
        w: 32,
        h: 48
    },
    bus_E: {
        x: 231,
        y: 1318,
        w: 36,
        h: 24
    },
    bus_N: {
        x: 415,
        y: 1285,
        w: 22,
        h: 29
    },
    bus_S: {
        x: 438,
        y: 1285,
        w: 22,
        h: 29
    },
    bus_W: {
        x: 268,
        y: 1318,
        w: 36,
        h: 24
    },
    bush: {
        x: 430,
        y: 1348,
        w: 16,
        h: 16
    },
    busStation_E: {
        x: 329,
        y: 1171,
        w: 48,
        h: 48
    },
    busStation_N: {
        x: 378,
        y: 1171,
        w: 48,
        h: 48
    },
    busStation_S: {
        x: 427,
        y: 1171,
        w: 48,
        h: 48
    },
    busStation_W: {
        x: 1,
        y: 1236,
        w: 48,
        h: 48
    },
    busStop_E: {
        x: 447,
        y: 1348,
        w: 16,
        h: 16
    },
    busStop_N: {
        x: 464,
        y: 1348,
        w: 16,
        h: 16
    },
    busStop_S: {
        x: 481,
        y: 1348,
        w: 16,
        h: 16
    },
    busStop_W: {
        x: 1,
        y: 1373,
        w: 16,
        h: 16
    },
    car_amber_E: {
        x: 305,
        y: 1318,
        w: 36,
        h: 24
    },
    car_amber_N: {
        x: 461,
        y: 1285,
        w: 22,
        h: 29
    },
    car_amber_S: {
        x: 484,
        y: 1285,
        w: 22,
        h: 29
    },
    car_amber_W: {
        x: 342,
        y: 1318,
        w: 36,
        h: 24
    },
    car_ems_E: {
        x: 379,
        y: 1318,
        w: 36,
        h: 24
    },
    car_ems_N: {
        x: 1,
        y: 1318,
        w: 22,
        h: 29
    },
    car_ems_S: {
        x: 24,
        y: 1318,
        w: 22,
        h: 29
    },
    car_ems_W: {
        x: 416,
        y: 1318,
        w: 36,
        h: 24
    },
    car_fire_E: {
        x: 453,
        y: 1318,
        w: 36,
        h: 24
    },
    car_fire_N: {
        x: 47,
        y: 1318,
        w: 22,
        h: 29
    },
    car_fire_S: {
        x: 70,
        y: 1318,
        w: 22,
        h: 29
    },
    car_fire_W: {
        x: 1,
        y: 1348,
        w: 36,
        h: 24
    },
    car_green_E: {
        x: 38,
        y: 1348,
        w: 36,
        h: 24
    },
    car_green_N: {
        x: 93,
        y: 1318,
        w: 22,
        h: 29
    },
    car_green_S: {
        x: 116,
        y: 1318,
        w: 22,
        h: 29
    },
    car_green_W: {
        x: 75,
        y: 1348,
        w: 36,
        h: 24
    },
    car_police_E: {
        x: 112,
        y: 1348,
        w: 36,
        h: 24
    },
    car_police_N: {
        x: 139,
        y: 1318,
        w: 22,
        h: 29
    },
    car_police_S: {
        x: 162,
        y: 1318,
        w: 22,
        h: 29
    },
    car_police_W: {
        x: 149,
        y: 1348,
        w: 36,
        h: 24
    },
    car_silver_E: {
        x: 186,
        y: 1348,
        w: 36,
        h: 24
    },
    car_silver_N: {
        x: 185,
        y: 1318,
        w: 22,
        h: 29
    },
    car_silver_S: {
        x: 208,
        y: 1318,
        w: 22,
        h: 29
    },
    car_silver_W: {
        x: 223,
        y: 1348,
        w: 36,
        h: 24
    },
    cone: {
        x: 18,
        y: 1373,
        w: 16,
        h: 16
    },
    crateFruit: {
        x: 35,
        y: 1373,
        w: 16,
        h: 16
    },
    crateVeg: {
        x: 52,
        y: 1373,
        w: 16,
        h: 16
    },
    detourE: {
        x: 69,
        y: 1373,
        w: 16,
        h: 16
    },
    detourN: {
        x: 86,
        y: 1373,
        w: 16,
        h: 16
    },
    detourS: {
        x: 103,
        y: 1373,
        w: 16,
        h: 16
    },
    detourW: {
        x: 120,
        y: 1373,
        w: 16,
        h: 16
    },
    dirt: {
        x: 137,
        y: 1373,
        w: 16,
        h: 16
    },
    doorHome: {
        x: 154,
        y: 1373,
        w: 16,
        h: 16
    },
    doorStore: {
        x: 171,
        y: 1373,
        w: 16,
        h: 16
    },
    grassA: {
        x: 188,
        y: 1373,
        w: 16,
        h: 16
    },
    grassB: {
        x: 205,
        y: 1373,
        w: 16,
        h: 16
    },
    home_0_E: {
        x: 344,
        y: 1236,
        w: 32,
        h: 32
    },
    home_0_N: {
        x: 377,
        y: 1236,
        w: 32,
        h: 32
    },
    home_0_S: {
        x: 410,
        y: 1236,
        w: 32,
        h: 32
    },
    home_0_W: {
        x: 443,
        y: 1236,
        w: 32,
        h: 32
    },
    home_1_E: {
        x: 476,
        y: 1236,
        w: 32,
        h: 32
    },
    home_1_N: {
        x: 1,
        y: 1285,
        w: 32,
        h: 32
    },
    home_1_S: {
        x: 34,
        y: 1285,
        w: 32,
        h: 32
    },
    home_1_W: {
        x: 67,
        y: 1285,
        w: 32,
        h: 32
    },
    home_2_E: {
        x: 100,
        y: 1285,
        w: 32,
        h: 32
    },
    home_2_N: {
        x: 133,
        y: 1285,
        w: 32,
        h: 32
    },
    home_2_S: {
        x: 166,
        y: 1285,
        w: 32,
        h: 32
    },
    home_2_W: {
        x: 199,
        y: 1285,
        w: 32,
        h: 32
    },
    home_3_E: {
        x: 232,
        y: 1285,
        w: 32,
        h: 32
    },
    home_3_N: {
        x: 265,
        y: 1285,
        w: 32,
        h: 32
    },
    home_3_S: {
        x: 298,
        y: 1285,
        w: 32,
        h: 32
    },
    home_3_W: {
        x: 331,
        y: 1285,
        w: 32,
        h: 32
    },
    office_1_E: {
        x: 66,
        y: 586,
        w: 64,
        h: 64
    },
    office_1_N: {
        x: 131,
        y: 586,
        w: 64,
        h: 64
    },
    office_1_S: {
        x: 196,
        y: 586,
        w: 64,
        h: 64
    },
    office_1_W: {
        x: 261,
        y: 586,
        w: 64,
        h: 64
    },
    office_2_E_E_0: {
        x: 326,
        y: 586,
        w: 64,
        h: 64
    },
    office_2_E_E_1: {
        x: 391,
        y: 586,
        w: 64,
        h: 64
    },
    office_2_E_E_2: {
        x: 1,
        y: 651,
        w: 64,
        h: 64
    },
    office_2_E_N_0: {
        x: 66,
        y: 651,
        w: 64,
        h: 64
    },
    office_2_E_N_1: {
        x: 131,
        y: 651,
        w: 64,
        h: 64
    },
    office_2_E_N_2: {
        x: 196,
        y: 651,
        w: 64,
        h: 64
    },
    office_2_E_N_3: {
        x: 261,
        y: 651,
        w: 64,
        h: 64
    },
    office_2_E_S_0: {
        x: 326,
        y: 651,
        w: 64,
        h: 64
    },
    office_2_E_S_1: {
        x: 391,
        y: 651,
        w: 64,
        h: 64
    },
    office_2_E_S_2: {
        x: 1,
        y: 716,
        w: 64,
        h: 64
    },
    office_2_E_S_3: {
        x: 66,
        y: 716,
        w: 64,
        h: 64
    },
    office_2_E_W_0: {
        x: 131,
        y: 716,
        w: 64,
        h: 64
    },
    office_2_E_W_1: {
        x: 196,
        y: 716,
        w: 64,
        h: 64
    },
    office_2_E_W_2: {
        x: 261,
        y: 716,
        w: 64,
        h: 64
    },
    office_2_E_W_3: {
        x: 326,
        y: 716,
        w: 64,
        h: 64
    },
    office_2_N_E_0: {
        x: 391,
        y: 716,
        w: 64,
        h: 64
    },
    office_2_N_E_1: {
        x: 1,
        y: 781,
        w: 64,
        h: 64
    },
    office_2_N_E_2: {
        x: 66,
        y: 781,
        w: 64,
        h: 64
    },
    office_2_N_E_3: {
        x: 131,
        y: 781,
        w: 64,
        h: 64
    },
    office_2_N_N_0: {
        x: 196,
        y: 781,
        w: 64,
        h: 64
    },
    office_2_N_N_1: {
        x: 261,
        y: 781,
        w: 64,
        h: 64
    },
    office_2_N_N_2: {
        x: 326,
        y: 781,
        w: 64,
        h: 64
    },
    office_2_N_S_0: {
        x: 391,
        y: 781,
        w: 64,
        h: 64
    },
    office_2_N_S_1: {
        x: 1,
        y: 846,
        w: 64,
        h: 64
    },
    office_2_N_S_2: {
        x: 66,
        y: 846,
        w: 64,
        h: 64
    },
    office_2_N_S_3: {
        x: 131,
        y: 846,
        w: 64,
        h: 64
    },
    office_2_N_W_0: {
        x: 196,
        y: 846,
        w: 64,
        h: 64
    },
    office_2_N_W_1: {
        x: 261,
        y: 846,
        w: 64,
        h: 64
    },
    office_2_N_W_2: {
        x: 326,
        y: 846,
        w: 64,
        h: 64
    },
    office_2_N_W_3: {
        x: 391,
        y: 846,
        w: 64,
        h: 64
    },
    office_2_S_E_0: {
        x: 1,
        y: 911,
        w: 64,
        h: 64
    },
    office_2_S_E_1: {
        x: 66,
        y: 911,
        w: 64,
        h: 64
    },
    office_2_S_E_2: {
        x: 131,
        y: 911,
        w: 64,
        h: 64
    },
    office_2_S_E_3: {
        x: 196,
        y: 911,
        w: 64,
        h: 64
    },
    office_2_S_N_0: {
        x: 261,
        y: 911,
        w: 64,
        h: 64
    },
    office_2_S_N_1: {
        x: 326,
        y: 911,
        w: 64,
        h: 64
    },
    office_2_S_N_2: {
        x: 391,
        y: 911,
        w: 64,
        h: 64
    },
    office_2_S_N_3: {
        x: 1,
        y: 976,
        w: 64,
        h: 64
    },
    office_2_S_S_1: {
        x: 66,
        y: 976,
        w: 64,
        h: 64
    },
    office_2_S_S_2: {
        x: 131,
        y: 976,
        w: 64,
        h: 64
    },
    office_2_S_S_3: {
        x: 196,
        y: 976,
        w: 64,
        h: 64
    },
    office_2_S_W_0: {
        x: 261,
        y: 976,
        w: 64,
        h: 64
    },
    office_2_S_W_1: {
        x: 326,
        y: 976,
        w: 64,
        h: 64
    },
    office_2_S_W_2: {
        x: 391,
        y: 976,
        w: 64,
        h: 64
    },
    office_2_S_W_3: {
        x: 1,
        y: 1041,
        w: 64,
        h: 64
    },
    office_2_W_E_0: {
        x: 66,
        y: 1041,
        w: 64,
        h: 64
    },
    office_2_W_E_1: {
        x: 131,
        y: 1041,
        w: 64,
        h: 64
    },
    office_2_W_E_2: {
        x: 196,
        y: 1041,
        w: 64,
        h: 64
    },
    office_2_W_E_3: {
        x: 261,
        y: 1041,
        w: 64,
        h: 64
    },
    office_2_W_N_0: {
        x: 326,
        y: 1041,
        w: 64,
        h: 64
    },
    office_2_W_N_1: {
        x: 391,
        y: 1041,
        w: 64,
        h: 64
    },
    office_2_W_N_2: {
        x: 1,
        y: 1106,
        w: 64,
        h: 64
    },
    office_2_W_N_3: {
        x: 66,
        y: 1106,
        w: 64,
        h: 64
    },
    office_2_W_S_0: {
        x: 131,
        y: 1106,
        w: 64,
        h: 64
    },
    office_2_W_S_1: {
        x: 196,
        y: 1106,
        w: 64,
        h: 64
    },
    office_2_W_S_2: {
        x: 261,
        y: 1106,
        w: 64,
        h: 64
    },
    office_2_W_S_3: {
        x: 326,
        y: 1106,
        w: 64,
        h: 64
    },
    office_2_W_W_1: {
        x: 391,
        y: 1106,
        w: 64,
        h: 64
    },
    office_2_W_W_2: {
        x: 1,
        y: 1171,
        w: 64,
        h: 64
    },
    office_2_W_W_3: {
        x: 66,
        y: 1171,
        w: 64,
        h: 64
    },
    plot: {
        x: 222,
        y: 1373,
        w: 16,
        h: 16
    },
    plotWorn: {
        x: 239,
        y: 1373,
        w: 16,
        h: 16
    },
    road0: {
        x: 256,
        y: 1373,
        w: 16,
        h: 16
    },
    road1: {
        x: 273,
        y: 1373,
        w: 16,
        h: 16
    },
    road10: {
        x: 290,
        y: 1373,
        w: 16,
        h: 16
    },
    road11: {
        x: 307,
        y: 1373,
        w: 16,
        h: 16
    },
    road12: {
        x: 324,
        y: 1373,
        w: 16,
        h: 16
    },
    road13: {
        x: 341,
        y: 1373,
        w: 16,
        h: 16
    },
    road14: {
        x: 358,
        y: 1373,
        w: 16,
        h: 16
    },
    road15: {
        x: 375,
        y: 1373,
        w: 16,
        h: 16
    },
    road2: {
        x: 392,
        y: 1373,
        w: 16,
        h: 16
    },
    road3: {
        x: 409,
        y: 1373,
        w: 16,
        h: 16
    },
    road4: {
        x: 426,
        y: 1373,
        w: 16,
        h: 16
    },
    road5: {
        x: 443,
        y: 1373,
        w: 16,
        h: 16
    },
    road6: {
        x: 460,
        y: 1373,
        w: 16,
        h: 16
    },
    road7: {
        x: 477,
        y: 1373,
        w: 16,
        h: 16
    },
    road8: {
        x: 494,
        y: 1373,
        w: 16,
        h: 16
    },
    road9: {
        x: 1,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_grey_b: {
        x: 18,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_grey_bl: {
        x: 35,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_grey_br: {
        x: 52,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_grey_l: {
        x: 69,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_grey_mid: {
        x: 86,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_grey_r: {
        x: 103,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_grey_t: {
        x: 120,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_grey_tl: {
        x: 137,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_grey_tr: {
        x: 154,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_pale_b: {
        x: 171,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_pale_bl: {
        x: 188,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_pale_br: {
        x: 205,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_pale_l: {
        x: 222,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_pale_mid: {
        x: 239,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_pale_r: {
        x: 256,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_pale_t: {
        x: 273,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_pale_tl: {
        x: 290,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_pale_tr: {
        x: 307,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_red_b: {
        x: 324,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_red_bl: {
        x: 341,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_red_br: {
        x: 358,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_red_l: {
        x: 375,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_red_mid: {
        x: 392,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_red_r: {
        x: 409,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_red_t: {
        x: 426,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_red_tl: {
        x: 443,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_red_tr: {
        x: 460,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_tan_b: {
        x: 477,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_tan_bl: {
        x: 494,
        y: 1390,
        w: 16,
        h: 16
    },
    roof_tan_br: {
        x: 1,
        y: 1407,
        w: 16,
        h: 16
    },
    roof_tan_l: {
        x: 18,
        y: 1407,
        w: 16,
        h: 16
    },
    roof_tan_mid: {
        x: 35,
        y: 1407,
        w: 16,
        h: 16
    },
    roof_tan_r: {
        x: 52,
        y: 1407,
        w: 16,
        h: 16
    },
    roof_tan_t: {
        x: 69,
        y: 1407,
        w: 16,
        h: 16
    },
    roof_tan_tl: {
        x: 86,
        y: 1407,
        w: 16,
        h: 16
    },
    roof_tan_tr: {
        x: 103,
        y: 1407,
        w: 16,
        h: 16
    },
    shopGlass: {
        x: 120,
        y: 1407,
        w: 16,
        h: 16
    },
    shopGlassL: {
        x: 137,
        y: 1407,
        w: 16,
        h: 16
    },
    shopGlassR: {
        x: 154,
        y: 1407,
        w: 16,
        h: 16
    },
    signBar: {
        x: 171,
        y: 1407,
        w: 16,
        h: 16
    },
    signDots: {
        x: 188,
        y: 1407,
        w: 16,
        h: 16
    },
    tree_amber: {
        x: 364,
        y: 1285,
        w: 16,
        h: 32
    },
    tree_green: {
        x: 381,
        y: 1285,
        w: 16,
        h: 32
    },
    tree_pine: {
        x: 398,
        y: 1285,
        w: 16,
        h: 32
    },
    wall_brick_l: {
        x: 205,
        y: 1407,
        w: 16,
        h: 16
    },
    wall_brick_m: {
        x: 222,
        y: 1407,
        w: 16,
        h: 16
    },
    wall_brick_one: {
        x: 239,
        y: 1407,
        w: 16,
        h: 16
    },
    wall_brick_r: {
        x: 256,
        y: 1407,
        w: 16,
        h: 16
    },
    wall_sand_l: {
        x: 273,
        y: 1407,
        w: 16,
        h: 16
    },
    wall_sand_m: {
        x: 290,
        y: 1407,
        w: 16,
        h: 16
    },
    wall_sand_one: {
        x: 307,
        y: 1407,
        w: 16,
        h: 16
    },
    wall_sand_r: {
        x: 324,
        y: 1407,
        w: 16,
        h: 16
    },
    wall_stone_l: {
        x: 341,
        y: 1407,
        w: 16,
        h: 16
    },
    wall_stone_m: {
        x: 358,
        y: 1407,
        w: 16,
        h: 16
    },
    wall_stone_one: {
        x: 375,
        y: 1407,
        w: 16,
        h: 16
    },
    wall_stone_r: {
        x: 392,
        y: 1407,
        w: 16,
        h: 16
    },
    windowFlat: {
        x: 409,
        y: 1407,
        w: 16,
        h: 16
    },
    windowHome: {
        x: 426,
        y: 1407,
        w: 16,
        h: 16
    },
    workSurface: {
        x: 443,
        y: 1407,
        w: 16,
        h: 16
    }
} as const;
export type FrameName = keyof typeof FRAMES;
